### ISSUE TITLE
[question] comparison with sh-chnode

### ISSUE THREAD

**Issue by FranklinYu** [tkareine/chnode#3]
First of all, thank you for building this and releasing under MIT license!

I read in the article that sh-chnode “includes some design decisions I didn’t like personally”. Would you mind listing those design decisions? I’d like to choose between sh-chnode and chnode; knowing their difference would help a lot.

By the way, “Automatic version switching” section mentions two ways to manage `PROMPT_COMMAND` in Bash. There is actually a third way: [bash-preexec](https://github.com/rcaloras/bash-preexec). Its implementation is more complicated than simply overriding `PROMPT_COMMAND`, but some readers *might* find it useful. (I don’t need it since I use Zsh.)

**Comment by tkareine** [comment]
Here are some differences between sh-chnode and the chnode of this project that mattered to me:

1. sh-chnode has non-compliant POSIX sh syntax in `chnode.sh` implementation (it would be better to stick with Bash/Zsh syntax, because that's what the tool reports to support).
2. sh-chnode loads Node.js installations from `/usr/local/Cellar/node` implicitly. Why affiliate the tool with Homebrew?
3. Continuing the previous point, sh-chnode has no option to specify a common root path for user's Node.js installations, from which Node versions would get picked automatically.
4. I happen to like the output of the `chruby` tool. To compare:

   chruby:

   ```
   $ chruby ruby-2
   $ chruby
    * ruby-2.7.2
      ruby-3.0.0
   ```

   sh-chnode:

   ```
   $ NODES=(~/.nodes/*); chnode node-14
   Switched to Node node-14.15.4 at /Users/tkareine/.nodes/node-14.15.4.
   $ chnode
   Usage: chnode [OPTIONS] VERSION
          chnode [OPTIONS] system

   Options:
   […]

   Available Node versions:
       node-14.15.4
       node-15.5.1
   ```

   chnode:

   ```
   $ chnode node-14
   $ chnode
    * node-14.15.4
      node-15.5.1
   ```

Thanks for suggesting Bash-Preexec, I expanded readme to cover how to use it with `chnode_auto`.
